<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>eip-worker-sync</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\Connector\Application\EIP.Data.Connector.Application.csproj" />
    <ProjectReference Include="..\Data\Connector\Infrastructure\EIP.Data.Connector.Infrastructure.csproj" />
    <ProjectReference Include="..\Data\Canonical\Application\EIP.Data.Canonical.Application.csproj" />
    <ProjectReference Include="..\Data\Canonical\Infrastructure\EIP.Data.Canonical.Infrastructure.csproj" />
    <ProjectReference Include="..\Data\DataLake\EIP.Data.DataLake.csproj" />
    <ProjectReference Include="..\Data\DataLake.Infrastructure\EIP.Data.DataLake.Infrastructure.csproj" />
    <ProjectReference Include="..\Data\Pipeline\EIP.Data.Pipeline.csproj" />
    <ProjectReference Include="..\BuildingBlocks\EIP.BuildingBlocks.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Data\EIP.BuildingBlocks.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="RabbitMQ.Client" Version="7.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

</Project>
