<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\EIP.Data.Warehouse.Domain.csproj" />
    <ProjectReference Include="..\..\Canonical\Application\EIP.Data.Canonical.Application.csproj" />
    <ProjectReference Include="..\..\Canonical\Domain\EIP.Data.Canonical.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\EIP.Shared.csproj" />
  </ItemGroup>

</Project>
